{
    'name': 'Zadarma Odoo Integration (Campscout)',
    'version': '1.5.0',
    'category': 'CRM',
    'summary': 'Інтеграція телефонії Zadarma: автоматичне збереження дзвінків, CRM, chatter',
    'author': 'Fayna',
    'website': 'https://fayna.company',
    'depends': ['base', 'crm', 'mail'],
    'data': [
        'security/zadarma_security.xml',
        'security/ir.model.access.csv',
        'views/zadarma_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/partner_lead_views.xml',
        'views/zadarma_import_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
