{
    'name': 'Zadarma Odoo Integration (Campscout)',
    'version': '1.3.0',
    'category': 'CRM',
    'summary': 'Hybrid Zadarma Integration: Lead Automation & SIP Mapping',
    'author': 'VladSh77',
    'depends': ['base', 'crm', 'mail'],
    'data': [
        'security/zadarma_security.xml',
        'security/ir.model.access.csv',
        'views/zadarma_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/partner_lead_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
